// Code generated by defc, DO NOT EDIT.

package transport

import (
	"net/rpc"

	"github.com/MoonshotAI/kimi-agent-sdk/go/wire"
)

func NewTransportClient(rpcClient *rpc.Client) Transport {
	return &implTransportClient{rpcClient: rpcClient}
}

type implTransportClient struct {
	rpcClient *rpc.Client
}

func (impl *implTransportClient) Prompt(params *wire.PromptParams) (*wire.PromptResult, error) {
	PromptRPCReply :=
		new(wire.PromptResult)
	PromptErr := impl.rpcClient.Call("Transport.Prompt", params, PromptRPCReply)
	if PromptErr != nil {
		return nil, PromptErr
	}
	return PromptRPCReply, nil
}

func (impl *implTransportClient) Cancel(params *wire.CancelParams) (*wire.CancelResult, error) {
	CancelRPCReply :=
		new(wire.CancelResult)
	CancelErr := impl.rpcClient.Call("Transport.Cancel", params, CancelRPCReply)
	if CancelErr != nil {
		return nil, CancelErr
	}
	return CancelRPCReply, nil
}

func (impl *implTransportClient) Event(event *wire.EventParams) (*wire.EventResult, error) {
	EventRPCReply :=
		new(wire.EventResult)
	EventErr := impl.rpcClient.Call("Transport.Event", event, EventRPCReply)
	if EventErr != nil {
		return nil, EventErr
	}
	return EventRPCReply, nil
}

func (impl *implTransportClient) Request(request *wire.RequestParams) (*wire.RequestResult, error) {
	RequestRPCReply :=
		new(wire.RequestResult)
	RequestErr := impl.rpcClient.Call("Transport.Request", request, RequestRPCReply)
	if RequestErr != nil {
		return nil, RequestErr
	}
	return RequestRPCReply, nil
}

func NewTransportServer(impl Transport) *TransportServer {
	return &TransportServer{
		implTransport: impl,
	}
}

type TransportServer struct {
	implTransport Transport
}

func (srv *TransportServer) Prompt(
	arg *wire.PromptParams,
	reply *wire.PromptResult,
) error {
	PromptRPCReply, PromptErr := srv.implTransport.Prompt(arg)
	if PromptErr != nil {
		return PromptErr
	}
	*reply = *PromptRPCReply
	return nil
}

func (srv *TransportServer) Cancel(
	arg *wire.CancelParams,
	reply *wire.CancelResult,
) error {
	CancelRPCReply, CancelErr := srv.implTransport.Cancel(arg)
	if CancelErr != nil {
		return CancelErr
	}
	*reply = *CancelRPCReply
	return nil
}

func (srv *TransportServer) Event(
	arg *wire.EventParams,
	reply *wire.EventResult,
) error {
	EventRPCReply, EventErr := srv.implTransport.Event(arg)
	if EventErr != nil {
		return EventErr
	}
	*reply = *EventRPCReply
	return nil
}

func (srv *TransportServer) Request(
	arg *wire.RequestParams,
	reply *wire.RequestResult,
) error {
	RequestRPCReply, RequestErr := srv.implTransport.Request(arg)
	if RequestErr != nil {
		return RequestErr
	}
	*reply = *RequestRPCReply
	return nil
}
